### PR TITLE
Add fixes for _win32_longpath

### LINKED ISSUE #33: UNC path breaks _win32_longpath()
I have, due to [DFS](https://en.wikipedia.org/wiki/Distributed_File_System_(Microsoft)) in my environment, tests running in a dfs path, which results in a [UNC](https://en.wikipedia.org/wiki/Path_(computing)#Universal_Naming_Convention) path (`\\my.domain\dfs\some\path`) being passed to copytree in `shared_datadir()`. This results in copytree failing with 
``` 
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '\\\\?\\\\\\my.domain\\dfs\\bla...
```
I traced this back to `return '\\\\?\\' + os.path.normpath(path)` in `plugin._win32_longpath()`, which afaict is not correct in case of a UNC path (see above UNC link). *Then* you need to insert an additional `UNC\`, so the prefix should be `'\\\\?\\UNC\\'` instead. UNC paths should be recognizable because they start with `\\`.

### PR DESCRIPTION
**Pull request by bilderbuchi**
This should fix #33.

I am not sure how I should test for this, as it depends on being on Windows and having UNC paths around.

### CODE REVIEW

**Comment by bilderbuchi** [comment]
I first push a test that should fail on Appveyor before adding a fix.

**Comment by nicoddemus** [comment]
> I am not sure how I should test for this, as it depends on being on Windows and having UNC paths around.

A unittest like the one you did looks sufficient. 👍

**Comment by bilderbuchi** [comment]
Ha, inspiration strikes, I just realised that the path does not have to _exist_ to check it.

Do you know what's up with [this test failure](https://ci.appveyor.com/project/gabrielcnr/pytest-datadir/builds/35754797#L144), that does not seem to be related to me?

**Comment by bilderbuchi** [comment]
OK, I am done, and it seems to work.

That CI failure from py35 onwards seems to be caused by a file having an overly long name, which Windows/Python does not deal gracefully with - dunno why this was not a problem before, or why not at lower Python versions?

**Comment by bilderbuchi** [comment]
Could the test collection failure be a pytest problem? I see it working with pytest-4.6.11, and failing with  pytest-6.1.11 where it was previously working with pytest-5.2.1.

**Comment by bilderbuchi** [comment]
Btw, I just realised you also have Travis tests, but they are not displayed in this PR checks field. I think there was a necessary change in the Travis-Github authentication that you had to do so that does not break. I think the Travis account owner needs to do [this](https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/#migrating-and-activating-all-repositories).

**Comment by gabrielcnr** [comment]
Hi @bilderbuchi - thanks for submitting this PR. We very much appreciate. I will take a look at this later this week and let you know about it. Stay tuned ;-)

**Comment by gabrielcnr** [comment]
I looked here and the change and the tests look good. Thanks @bilderbuchi 

I don't work on Windows, so it took me some effort to test this on Windows.
The first thing is actually cloning the git repo on Windows failed because of the Windows path length limit/constraint. @nicoddemus I don't think we should have the test file committed there. Probably it would be worth generating it dynamically on the test. This may help to explain the problems on AppVeyor too.

image

**Comment by bilderbuchi** [comment]
OK, do you need anything from me here to proceed?

Btw, you'll probably have to test that "dynamically creating" the files actually works correctly (e.g. in a separate PR), I expect you will run into problems because *Windows* will also refuse to create those files. :-P

**Comment by bilderbuchi** [comment]
@gabrielcnr @nicoddemus do you still plan on merging this PR?

**Comment by nicoddemus** [comment]
@bilderbuchi I believe so yes!

I suggest to add the "long file" again, and rebase on `master`, to see if it will not present problems with GH Actions.

**Comment by bilderbuchi** [comment]
> I suggest to add the "long file" again

I'm not sure what you mean, that long file business was AFAICT unrelated to this PR, which is about the UNC path prefixing (#33).

I'll rebase when I get the opportunity.

**Comment by nicoddemus** [comment]
> I'm not sure what you mean, that long file business was AFAICT unrelated to this PR, which is about the UNC path prefixing (https://github.com/gabrielcnr/pytest-datadir/issues/33).

I meant regarding this comment:

> The first thing is actually cloning the git repo on Windows failed because of the Windows path length limit/constraint. @nicoddemus I don't think we should have the test file committed there.

which lead me to think there was a long file committed in the PR? Or I misunderstood and that was unrelated to the PR?

**Comment by nicoddemus** [comment]
Ahh reading the other issues for context seems the "large file" was another thing entirely, please disregard that. 👍

**Comment by bilderbuchi** [comment]
Rebased. Note though that I don't have access to that Windows machine anymore, so I could not run the tests locally.

**Comment by nicoddemus** [comment]
Thanks @bilderbuchi, appreciate the patience!

LGTM! I took the liberty of adding a CHANGELOG entry.

Will merge in the next few days to give others a chance to review. 👍

**Comment by bilderbuchi** [comment]
Thanks, my pleasure!

**Pull request merged**
