### PR TITLE
Support directories and use shutil.copytree() on them

### PR DESCRIPTION
**Pull request by edisongustavo**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @edisongustavo! Could you please add a test for the fix?

**Comment by edisongustavo** [comment]
Sure, I didn't see the tests there for some reason...

**Comment by gabrielcnr** [comment]
Thank you both. I'll wait for the tests then I'm happy to merge.

**Comment by edisongustavo** [comment]
@nicoddemus @gabrielcnr done

**Comment by nicoddemus** [comment]
LGTM! Tests also pass for me locally.

**Comment by gabrielcnr** [comment]
Awesome. Thank you @edisongustavo.

**Pull request merged**
