### PR TITLE
Support for windows long filenames in datadir and shared_datadir fixtures

### PR DESCRIPTION
**Pull request by tarcisiofischer**

### CODE REVIEW

**Comment by tarcisiofischer** [comment]
Seems to be working on Windows, but you must enable the job on appveyor (I don't have the credentials to do so).
Details here: https://ci.appveyor.com/project/tarcisiofischer/pytest-datadir/builds/21614433

This PR solves the problem when I have a long filepath inside a datadir and/or when my "tmp" directory is too long on Windows.

`git config --system core.longpaths true` is necessary to clone from now on, since the test file I've added have a long name.

Marking @nicoddemus since it seems to be the most active member (Based on the commit history).

**Comment by nicoddemus** [comment]
Enabled AppVeyor, thanks for that. A new build will start on the next push. 👍

**Comment by nicoddemus** [comment]
Awesome, I can confirm the test fails without the `_win32_longpathpath` function. 👍

**Comment by nicoddemus** [comment]
I'm going ahead and merge this even though we don't have AppVeyor configured yet. I will look into this later with @gabrielcnr. 👍

**Pull request merged**
